# Run on a schedule
trigger: none
pr: none

jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.15'
  steps:
  - template: common-validation.yml
    parameters:
      runTests: false
      runFrameworkTests: true

- job: Linux
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - template: common-validation.yml
    parameters:
      runTests: false
      runFrameworkTests: true
